obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.3325
inflation_radius: 0.55

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: camera_depth_frame, data_type: PointCloud, topic: /camera/depth/points/PointCloud2, marking: true, clearing: true}
